### ISSUE TITLE
Add a config option to use a certain font in a translation

### ISSUE THREAD

**Issue by Nordblum** [Muchaszewski/DSP_TranslationMod#1]
Game's default font doesn't work well with Cyrillic letters, so being able to specify font's name in translation's config would be great for readability. Either system-installed fonts or the ones in translation's folder could be used, the latter being more optimal and compatible IMO.

**Comment by Nordblum** [comment]
Here's the screenshots of Russian translation. Notice the spacing between the letters, most words don't even fit.
[Main menu](https://i.imgur.com/tVYd80J.jpg)
[Loading screen](https://i.imgur.com/bznHKRH.jpg)
[Research window](https://i.imgur.com/WC7ZNCM.jpg)

**Comment by Muchaszewski** [comment]
As of 0.2.0, there is a possibility to choose the font from the in-game menu. But this is a work in progress and text adjustments were not yet implemented!

![image](https://user-images.githubusercontent.com/5092066/107992055-35bb0480-6fd8-11eb-8c30-5bd4244044f8.png)
Just change to something matching style of the game :)
