### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by ardthast** [Muchaszewski/DSP_TranslationMod#9]
i get this error when I try to enter the game.I tried most things including deleting and installing the game.I was able to log in when I uninstalled the plugin and entered it

![Ekran görüntüsü 2024-01-28 145141](https://github.com/Muchaszewski/DSP_TranslationMod/assets/157961555/f91d461f-4b6b-46b2-b8d6-821b8f72b2c7)
![Ekran ](https://github.com/Muchaszewski/DSP_TranslationMod/assets/157961555/8d7f0627-8d02-48e1-8476-b3163a8d98e2)

**Comment by limoka** [comment]
The mod is outdated, and atm adding translations is possible without mods, or by using a different setup: https://discord.gg/8xJH9Uj5
